### ISSUE TITLE
Get json additionally

### ISSUE THREAD

**Issue by geek-merlin** [TomasVotruba/phpunit-json-result#1]
Nice package!

I want to eat my result cake and have it:
- See the test results pretty-printed while running
- Use them as json in script after test run

Is this or can this be made possible? Maybe by dumping json to a well-known file name?

**Comment by TomasVotruba** [comment]
You can pipe it as any other bash result:
https://superuser.com/questions/461946/can-i-use-pipe-output-as-a-shell-script-argument

Or store it to a file first:

```bash
vendor/bin/phpunit >> result.json
```
