### ISSUE TITLE
Logging support?

### ISSUE THREAD

**Issue by floriankraemer** [TomasVotruba/phpunit-json-result#4]
Is it possible to use the logging functionality of PHPUnit?

I've tried this but it doesn't do anything, no error but also no json file is created.

```xml
  <logging>
      <junit outputFile="tmp/test-artifacts/phpunit.xml"/>
      <json outputFile="tmp/test-artifacts/phpunit.json"/>
  </logging>
```

**Comment by TomasVotruba** [comment]
Not that I'm aware off. This simply outputs final result in json, nothing fancier.
