### ISSUE TITLE
Compatibility with PHP 8.1

### ISSUE THREAD

**Issue by KoloboIsMe** [TomasVotruba/phpunit-json-result#5]
My project is in PHP 8.1 and I wish to use your extension.

It needs phpUnit 10.5 at least ; but this version of phpUnit requires PHP 8.2.

Is there any way to make it work ? Maybe with an older version of this project ?

**Comment by TomasVotruba** [comment]
Thanks for checking. I think PHPUnit 9.x does have json result in itself, doesn't it? 
I made this package to get the same from PHPUnit 10.x.

Architecture of PHPUnit 9.x events is completeely different, so not sure if this package would work there.

**Comment by KoloboIsMe** [comment]
Thank you very much for your fast answer.

I am confused because it says [here ](https://phpunit.de/supported-versions.html)that phpUnit 10.X is compatible with PHP 8.1.

I can't find anything about JSON format for phpUnit 9.X, but there is something about XML format. It could do the job, I will check this out. :)

**Comment by TomasVotruba** [comment]
I see. I think we can lower this PHP version here to PHP 8.1: https://github.com/TomasVotruba/phpunit-json-result/blob/b488ab44ad9865c958d8a8ad43d249f3c635384a/composer.json#L6

Could you send PR? :)
